#!/bin/sh
JAVA=java
UNZIP=unzip
JAR=`dirname $0`/../bin/dex2sex.jar
APK_FILE=${1}
OUTPUT=`basename "${1}" .apk`
TMPDIR=/tmp/dex2sex/

mkdir -p ${TMPDIR}
${UNZIP} ${APK_FILE} classes.dex -d ${TMPDIR}
mkdir -p ${OUTPUT}
${JAVA} -jar ${JAR} -d ${OUTPUT} ${TMPDIR}/classes.dex
rm ${TMPDIR}/classes.dex
for i in `find ${OUTPUT} -name '*.sxddx'`
do
    sed 's/\[array .*\]\//array\//g' $i > ${TMPDIR}/tmp.txt
    mv ${TMPDIR}/tmp.txt $i
done
