#!/bin/sh
if [ $# -eq 0 ]; then
	echo "Disassemble a signle java file to S-Expression Represented Dalivk Bytecode" >&1
	echo "Usage: $0 filename.java [outputdir]" >&1
	echo "This command will compile and disassemble file and produce the output to ouputdir, if outputdir is omitted the output will produced in current working directory" >&1
	exit 1
fi

[ -z ${2} ] && BASEDIR=. || BASEDIR=$2
JAVA=java
JAVAC=javac
JAR=`dirname $0`/../bin/dex2sex.jar
DX=`dirname $0`/../bin/dx
SOURCE=${1}
OUTPUT=${BASEDIR}
PREFIX=`basename ${SOURCE} .java`
TMPDIR=/tmp/dex2sex
LANDROID=`dirname $0`/../bin/lib/android.jar

if [ -z "`echo ${DX}|grep '^/'`" ]; then
	DX=`pwd`/${DX}
fi

mkdir -p ${TMPDIR}/build
rm -rf ${TMPDIR}/build/*
find ${SOURCE} -name "*.java" -and -type f > ${TMPDIR}/build/sources.list
if ${JAVAC} -target 1.6 -source 1.6 -cp .:${LANDROID} -d ${TMPDIR}/build/ @${TMPDIR}/build/sources.list 2> ${TMPDIR}/build/build.log; then
	echo >/dev/null
else
	cat ${TMPDIR}/build/build.log >&1
	exit 1
fi
PREV_PWD=`pwd`
cd ${TMPDIR}/build
find . -name '*.class' > ${TMPDIR}/build/classes.list
if ${DX} --dex --output=${TMPDIR}/${PREFIX}.dex `cat ${TMPDIR}/build/classes.list`; then
	echo >/dev/null
else
	rm -rf ${TMPDIR}/build
	echo "Can not build .dex file from the class" >&1
	exit 1
fi
cd ${PREV_PWD}
if ${JAVA} -jar ${JAR} -d ${OUTPUT} ${TMPDIR}/${PREFIX}.dex; then
	echo >/dev/null
else
	rm -rf ${TMPDIR}/build ${TMPDIR}/${PREFIX}.dex
	echo "Can not disassemble .dex file" >&1
	exit 1
fi
sed 's/class$/sxddx/g' ${TMPDIR}/build/classes.list > ${TMPDIR}/build/sxddx.list
for i in `cat ${TMPDIR}/build/sxddx.list`
do
    sed 's/\[array .*\]\//java\/lang\/reflect\/Array\//g' ${OUTPUT}/${i} > ${TMPDIR}/tmp.txt
    mv ${TMPDIR}/tmp.txt ${OUTPUT}/${i}
done

rm -rf ${TMPDIR}/${PREFIX}.dex ${TMPDIR}/build
